bbms/Pages/donation/Index.cshtml.cs
using bbms.Pages.BStock;
using bbms.Pages.transfare;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Data;
using System.Data.SqlClient;
using System.Text.RegularExpressions;

namespace bbms.Pages.donation
{
    public class IndexModel : PageModel
    {

        string connectionString = "Data Source=DESKTOP-9DNNVCS\\SQLEXPRESS;Initial Catalog=blooddb;Integrated Security=True";
        public string datamsg = "";
        public string successmsg = "";

		public List<binfo> blist = new List<binfo>();
        public List<dinfo> dlist = new List<dinfo>();
        public dinfo donate = new dinfo();

        int oldstock;
        public void OnGet()
        {
			try
			{
				SqlConnection con = new SqlConnection(connectionString);
				con.Open();
				string sql = "select * from bstock";
				SqlCommand cmd = new SqlCommand(sql, con);
				SqlDataReader reader = cmd.ExecuteReader();
				while (reader.Read())
				{
					binfo info = new binfo();
					info.id = reader.GetInt32(0);
					info.bgroup = reader.GetString(1);
					info.amount = reader.GetString(2);
					blist.Add(info);
				}
			}
			catch (Exception ex)
			{
				//errormsg = ex.Message;
				return;
			}

            try
            {
                SqlConnection con = new SqlConnection(connectionString);
                con.Open();
                string sql = "select * from donors where Status = 'Accepted'";
                SqlCommand cmd = new SqlCommand(sql, con);
                SqlDataReader reader = cmd.ExecuteReader();
                while (reader.Read())
                {
                    dinfo info = new dinfo();
                    info.id = reader.GetInt32(0);
                    info.name = reader.GetString(1);
                    info.bgroup = reader.GetString(6);
                    dlist.Add(info);
                }
            }
            catch (Exception ex)
            {
                //errormsg = ex.Message;
                return;
            }

            try
            {

                string id = Request.Query["id"];

                SqlConnection sqlConnection = new SqlConnection(connectionString);
                sqlConnection.Open();
                string sql = "SELECT * FROM donors where DonorID = '" + id + "'";
                SqlCommand cmd = new SqlCommand(sql, sqlConnection);
                SqlDataReader reader = cmd.ExecuteReader();
                while (reader.Read())
                {

                   donate.id = reader.GetInt32(0);
                   donate.name = reader.GetString(1);
                   donate.bgroup = reader.GetString(6);
                }

            }
            catch (Exception ex)
            {
                //errormsg = ex.Message;
            }

            
        }
        
        public void OnPostDonate(string bgroup)
        {
            SqlConnection connection = new SqlConnection(connectionString);
            connection.Open();
            string query = "SELECT * FROM bstock where BGrouo = '" + bgroup + "'";
            SqlCommand cmd1 = new SqlCommand(query, connection);
            SqlDataAdapter sda = new SqlDataAdapter(cmd1);
            DataTable dt = new DataTable();
            sda.Fill(dt);
            foreach (DataRow dr in dt.Rows)
            {
                oldstock = Convert.ToInt32(dr["Amount"].ToString());
            }
            connection.Close();

            try
            {
                string blodgroup = Request.Form["bgroup"];
                int stock = oldstock +1;
                SqlConnection conn = new SqlConnection(connectionString);
                conn.Open();
                string sql = "UPDATE bstock SET Amount = '" + stock + "' where BGrouo = '" + blodgroup + "' ";
                SqlCommand command = new SqlCommand(sql, conn);
                command.ExecuteNonQuery();

            }
            catch (Exception ex)
            {
                datamsg = ex.Message;
            }
            Response.Redirect("/donation/Index");
        }
    }

	public class binfo
	{
		public int id;
		public string bgroup;
		public string amount;

	}

    public class dinfo
    {
        public int id;
        public string name;
        public string bgroup;

    }
}

bbms/Pages/donation/Index.cshtml
@page
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@using Microsoft.AspNetCore.Http;
@inject IHttpContextAccessor HttpContextAccessor;

@model bbms.Pages.donation.IndexModel
@{
}
@if (@HttpContextAccessor.HttpContext.Session.GetString("user") == null)
{
    Response.Redirect("/Index");
}
@if (Model.datamsg.Length > 0)
{
    <div class="alert alert-danger text-dark alert-dismissible fade show" role="alert">
        @Model.datamsg
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">x</button>
    </div>
}

@if (Model.successmsg.Length > 0)
{
    <div class="alert alert-info text-dark alert-dismissible fade show" role="alert">
        @Model.successmsg
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">x</button>
    </div>
}

<body class="bg-content">
    <main class="dashboard">
        <div class="container">
            <center>
                <h1 style=" font-family : Tahoma; font-weight : bolder; color :var(--sidebar-color);"> Blood Bank System</h1>
                <h2 style=" font-family : Tahoma; font-weight : bolder; color :var(--sidebar-color);">Donation</h2>
                <i class="fas fa-droplet" style="color :var(--sidebar-color);"></i>
            </center>
            <br />
            <div class="row">
                <div class="col">

                    <div class="slide-container">
                        <div class="slide-content">
                            <div class="card-wrapper">
                                <h3 style="font-family:Tahoma; font-weight:700; text-align:center; color:#dc3545; ">Blood List</h3>
                                <table class="table table-bordered table-stripped" style="width: 90%;">
                                    <thead class="bg-danger text-white" style="font-family:Tahoma; text-align:center; font-size:16px; font-weight:700;">
                                    <tr>
                                    <th>BID</th>
                                    <th>BGroup</th>
                                    <th>Amount</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                        @foreach (var row in Model.blist)
                                        {
                                            <tr style="color: red; font-family:Tahoma; text-align:center; font-size:16px; font-weight:700;">
                                                <td>@row.id</td>
                                                <td>@row.bgroup</td>
                                                <td>@row.amount</td>
                                            </tr>
                                        }
                                    </tbody>

                                    <tfoot>
                                        <tr class="" style="background:red">
                                            <td colspan="3" style="height: 10px"></td>
                                        </tr>
                                    </tfoot>


                                </table>
                            </div>
                        </div>
                    </div>

                </div>

                <div class="col">

                    <form method="POST">

                        <div class="content">
                            <input type="hidden" name="id" value="@Model.donate.id" />

                            <div class="inputbox">
                                <label>Donor Name</label>
                                <input type="text" readonly name="name" value="@Model.donate.name" required autocomplete="off" />
                            </div>
                            <div class="inputbox">
                                <label>Blood Group</label>
                                <input type="text" readonly name="bgroup" value="@Model.donate.bgroup" required autocomplete="off" />
                            </div>
                        </div>
                        <center>
                            <button name="donate" id="btnDonate" asp-page-handler="Donate" type="submit" class="btns"><i class="fas fa-hand-holding-droplet"></i>&nbsp; &nbsp;Donate</button>
                        </center>
                    </form>

                </div>
</div>


        </div>
        <div class="slide-container">
            <div class="slide-content">
                <div class="card-wrapper">
                    <table class="table table-bordered table-stripped" id="mytable" style="width: 120%;">
                        <thead class="bg-danger text-white" style="font-family:Tahoma; text-align:center; font-size:16px; font-weight:700;">
                            <tr>
                                <th>DID</th>
                                <th>DName</th>
                                <th>BGroup</th>
                                <th>Action</th>
                            </tr>
                        </thead>

                        <tbody>
                            @foreach (var row in Model.dlist)
                            {
                                <tr style="color: red; font-family:Tahoma; text-align:center; font-size:16px; font-weight:700;">
                                    <td>@row.id</td>
                                    <td>@row.name</td>
                                    <td>@row.bgroup</td>
                                    <td>
                                        <a href="/donation/Index?id=@row.id" class="btn btn-success btn-sm text-light"><i class="fas fa-pen"></i></a>
                                    </td>
                                </tr>
                            }
                        </tbody>

                        <tfoot>
                            <tr class="" style="background:red">
                                <td colspan="4" style="height: 10px"></td>
                            </tr>
                        </tfoot>


                    </table>
                </div>
            </div>
        </div>
        
</main>
</body>

<style>

    .content {
        display: flex;
        flex-wrap: wrap;
        justify-content: space-between;
        padding: 20px 0;
    }


    .inputbox {
        display: flex;
        flex-wrap: wrap;
        width: 50%;
        padding-bottom: 15px;
    }

        .inputbox:nth-child(2n) {
            justify-content: space-between;
        }

    .select-box:nth-child(4n) {
        justify-content: space-between;
    }

    .inputbox label {
        width: 95%;
        color: #dc3545;
        font-weight: bold;
        margin: 5px 0;
        text-align: left;
    }



    .inputbox input {
        height: 40px;
        width: 95%;
        padding: 0 10px;
        border-radius: 5px;
        border: 2px solid #dc3545;
        outline: none;
        display: flex;
        font-weight: 600;
        font-size: 18px;
        color: #dc3545;
        background: transparent;
    }

        .inputbox input:is(:focus, :valid) {
            box-shadow: 0 3px 6px rgba(0,0,0,0.2);
        }

    .selectbox {
        display: flex;
        flex-wrap: wrap;
        width: 50%;
        padding-bottom: 15px;
    }

        .selectbox select {
            height: 40px;
            width: 95%;
            padding: 0 10px;
            border-radius: 5px;
            border: 2px solid #dc3545;
            outline: none;
            background: transparent;
            color: #dc3545;
            font-weight: bolder;
        }

            .selectbox select:is(:focus, :valid) {
                box-shadow: 0 3px 6px rgba(0,0,0,0.2);
            }

        .selectbox label {
            width: 95%;
            color: #dc3545;
            font-weight: bold;
            margin: 5px 3px;
            text-align: left;
        }


    .btns {
        width: 40%;
        padding: 7px;
        font-weight: bolder;
        font-size: 20px;
        color: #fff;
        border: .2rem solid #dc3545;
        border-radius: 5px;
        background: #dc3545;
    }

        .btns:hover {
            background: transparent;
            color: #dc3545;
        }

    .dataTables_length label {
        color: #dc3545;
        font-size: 20px;
        font-weight: bold;
        font-family: Tahoma;
    }

    .dataTables_length select {
        height: 40px;
        width: 35%;
        padding: 0 10px;
        border-radius: 5px;
        border: 2px solid #dc3545;
        outline: none;
        background: transparent;
        color: #dc3545;
        font-weight: bolder;
        margin-bottom: 1rem;
    }

    .dataTables_filter input {
        height: 40px;
        width: 80%;
        padding: 0 10px;
        border-radius: 5px;
        border: 2px solid #dc3545;
        outline: none;
        font-weight: 600;
        font-size: 18px;
        color: #dc3545;
        background: transparent;
    }

    .dataTables_filter label {
        color: #dc3545;
        font-weight: bold;
        margin: 5px 0;
    }

    #mytable_info {
        color: #dc3545;
        font-size: 20px;
        font-weight: bold;
        font-family: Tahoma;
    }

    .paginate_button.previous,
    .paginate_button.next {
        color: #dc3545;
        font-size: 20px;
        font-weight: bold;
        font-family: Tahoma;
    }

    a.paginate_button.current {
        padding: 7px;
        font-weight: bolder;
        font-size: 20px;
        color: #fff;
        border: .2rem solid #dc3545;
        border-radius: 5px;
        background: #dc3545;
    }

    .dt-buttons button.dt-button {
        padding: 7px;
        font-weight: bolder;
        font-size: 16px;
        border: .2rem solid #dc3545;
        border-radius: 5px;
        background: transparent;
        color: #dc3545;
    }

        .dt-buttons button.dt-button:hover {
            color: #fff;
            background: #dc3545;
        }

    button.dt-button.button-page-length.active:hover {
        color: #dc3545;
    }

    button.dt-button.buttons-columnVisibility.active {
        color: #dc3545;
    }
</style>

<script type="text/javascript">
    $(document).ready(function () {
        $('#mytable').DataTable({
            //"order": [0,asc],
            order: [0, 'desc'],

            mark: true,
            dom: 'Bfrtip',
            lengthMenu: [
                [10, 25, 50, 100, -1],
                ['10 rows', '25 rows', '50 rows', '100 rows', 'Show All']
            ],





            buttons: [
                'pageLength',
                {
                    extend: 'copyHtml5',
                    exportOptions: {
                        columns: ':visible'
                    }
                },
                {
                    extend: 'excelHtml5',
                    exportOptions: {
                        columns: ':visible'
                    }
                },
                {
                    extend: 'csvHtml5',
                    exportOptions: {
                        columns: ':visible'
                    }
                },

                {
                    extend: 'pdfHtml5',
                    // download: 'open',
                    exportOptions: {
                        columns: ':visible'
                    }

                },
                {
                    extend: 'print',
                    exportOptions: {
                        columns: ':visible'
                    }
                },
                'colvis'
            ],
            columDefs: [{
                targets: -1,
                visible: false
            }]


        });
    });
</script>