bbms/Pages/transfare/Index.cshtml.cs
using bbms.Pages.patients;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Data;
using System.Data.SqlClient;
using System.Text.RegularExpressions;

namespace bbms.Pages.transfare
{
    public class IndexModel : PageModel
    {
        string connectionString = "Data Source=DESKTOP-9DNNVCS\\SQLEXPRESS;Initial Catalog=blooddb;Integrated Security=True";
        public string errormsg = "";
        public string successmsg = "";
        public List<pinfo> plist = new List<pinfo>();
        public pinfo pinfo = new pinfo();

        int newstock;
        public void OnGet()
        {
            try
            {
                SqlConnection con = new SqlConnection(connectionString);
                con.Open();
                string sql = "select * from patient";
                SqlCommand cmd = new SqlCommand(sql, con);
                SqlDataReader reader = cmd.ExecuteReader();
                while (reader.Read())
                {
                    pinfo info = new pinfo();
                    info.id = reader.GetInt32(0);
                    info.name = reader.GetString(1);
                    info.age = reader.GetString(2);
                    info.gender = reader.GetString(3);
                    info.bgroup = reader.GetString(6);
                    plist.Add(info);
                }
            }
            catch (Exception ex)
            {
                errormsg = ex.Message;
                return;
            }

            try
            {

                string id = Request.Query["id"];

                SqlConnection sqlConnection = new SqlConnection(connectionString);
                sqlConnection.Open();
                string sql = "SELECT * FROM patient where PatID = '" + id + "'";
                SqlCommand cmd = new SqlCommand(sql, sqlConnection);
                SqlDataReader reader = cmd.ExecuteReader();
                while (reader.Read())
                {

                    pinfo.id = reader.GetInt32(0);
                    pinfo.name = reader.GetString(1);
                    pinfo.age = reader.GetString(2);
                    pinfo.gender = reader.GetString(3);
                    pinfo.bgroup = reader.GetString(6);
                }

            }
            catch (Exception ex)
            {
                errormsg = ex.Message;
            }
        }

        public void OnPostTransfare()
        {
			string blodtran = Request.Form["blodtran"];
			SqlConnection connection = new SqlConnection(connectionString);
            connection.Open();
            string query = "SELECT * FROM bstock where BGrouo = '" + blodtran + "'";
            SqlCommand cmd1 = new SqlCommand(query, connection);
            SqlDataAdapter sda = new SqlDataAdapter(cmd1);
            DataTable dt = new DataTable();
            sda.Fill(dt);
            foreach (DataRow dr in dt.Rows)
            {
                newstock = Convert.ToInt32(dr["Amount"].ToString());
            }
            connection.Close();
			try
			{
				string id = Request.Form["id"];
				string name = Request.Form["name"];
				string age = Request.Form["age"];
				string gender = Request.Form["gender"];
				string blodgroup = Request.Form["bgroup"];
				
				string date = Request.Form["date"];

				int stock = newstock - 1;

				SqlConnection conn = new SqlConnection(connectionString);
				conn.Open();
				if (newstock > 0)
				{
					string sql = "UPDATE bstock SET Amount = " + stock + " where BGrouo = '" + blodtran + "' ";
					SqlCommand command = new SqlCommand(sql, conn);
					command.ExecuteNonQuery();


					string qry = "INSERT INTO transfare (CID, CName, Gender, Age, BGroup ,Btansfare, Date) VALUES('" + id + "', '" + name + "', '" + gender + "', '" + age + "', '" + blodgroup + "', '" + blodtran + "', '" + date + "')";
					SqlCommand sqlCommand = new SqlCommand(qry, conn);
					sqlCommand.ExecuteNonQuery();
					successmsg = "Blood transfusion done successfully";
				}
				else
				{
					errormsg = "We are sorry the stock not available please choose onther one that matching";
				}


			}
			catch (Exception ex)
			{
				errormsg = ex.Message;
			}

		}

        
    }

    public class pinfo
    {
        public int id;
        public string name;
        public string age;
        public string gender;
        public string bgroup;
    }
}

bbms/Pages/transfare/Index.cshtml
@page
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@using Microsoft.AspNetCore.Http;
@inject IHttpContextAccessor HttpContextAccessor;


@model bbms.Pages.transfare.IndexModel
@{
}

@if (@HttpContextAccessor.HttpContext.Session.GetString("user") == null)
{
    Response.Redirect("/Index");
}
@if (Model.errormsg.Length > 0)
{
    <div class="alert alert-danger text-dark alert-dismissible fade show" role="alert">
        @Model.errormsg
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">x</button>
    </div>
}

@if (Model.successmsg.Length > 0)
{
    <div class="alert alert-info text-dark alert-dismissible fade show" role="alert">
        @Model.successmsg
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">x</button>
    </div>
}
<body class="bg-content">

    <main class="dashboard">
        <div class="container">

            <br />
            <center>
                <h1 style=" font-family : Tahoma; font-weight : bolder; color :var(--sidebar-color);"> Blood Bank System</h1>
                <h2 style=" font-family : Tahoma; font-weight : bolder; color :var(--sidebar-color);">Transfusion</h2>
                <i class="fas fa-droplet" style="color :var(--sidebar-color);"></i>
            </center>

            <form method="POST">

                <div class="content">
                    <div class="inputbox">
                        <label>Patient Name</label>
                        <input type="text" name="name" readonly required value="@Model.pinfo.name" autocomplete="off" />
                        <input type="hidden" name="id" value="@Model.pinfo.id" readonly />
                    </div>

                    <div class="inputbox">
                        <label>Patient Age</label>
                        <input type="text" name="age" readonly value="@Model.pinfo.age" required autocomplete="off" />
                    </div>
                    <div class="inputbox">
                        <label>Patient Gender</label>
                        <input type="text" name="gender" readonly value="@Model.pinfo.gender" required autocomplete="off" />
                    </div>

                    <div class="inputbox">
                        <label>Blood Group</label>
                        <input type="text" name="bgroup" readonly autocomplete="off" value="@Model.pinfo.bgroup" />
                    </div>

                    <div class="inputbox">
                        <label>Blood Tran</label>
                        <input type="text" name="blodtran" autocomplete="off"  required/>
                    </div>

                    <div class="inputbox">
                        <label>Date</label>
                        <input type="date" name="date" autocomplete="off" required/>
                    </div>
                </div>
                <center>
                    <button name="transafre" id="btnTransfare" asp-page-handler="Transfare" type="submit" class="btns"><i class="fas fa-exchange"></i> Transafare</button>
                </center>
            </form>
            <br /><br />
            <div class="row">
               <div class="col">
                                    <h3 style="font-family:Tahoma; font-weight:700; text-align:center; color:#dc3545; ">Matching Table</h3>
                                    <img src="~/images/match.PNG" width="100%" height="100%"/>
                            </div>
               
               <div class="col">

                    
                                <h3 style="font-family:Tahoma; font-weight:700; text-align:center; color:#dc3545; ">Donors List</h3>
                                <table class="table table-bordered table-stripped" id="mytable" style="width: 140%;">
                                    <thead class="bg-danger text-white" style="font-family:Tahoma; text-align:center; font-size:16px; font-weight:700;">
                                        <tr>
                                        <th>PID</th>
                                        <th>PName</th>
                                        <th>Gender</th>
                                        <th>PAge</th>
                                        <th>BGroup</th>
                                        <th>Action</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                            @foreach (var row in Model.plist)
                            {
                                <tr style="color: red; font-family:Tahoma; text-align:center; font-size:16px; font-weight:700;">
                                    <td class="patient_id">@row.id</td>
                                    <td>@row.name</td>
                                    <td>@row.gender</td>
                                    <td>@row.age</td>
                                    <td>@row.bgroup</td>
                                    <td>
                                        <a href="/transfare/Index?id=@row.id" class="btn btn-success btn-sm text-light"><i class="fas fa-pen"></i></a>
                                    </td>

                                </tr>
                            }
                                    </tbody>

                                    <tfoot>
                                        <tr class="" style="background:red">
                                            <td colspan="6" style="height: 10px"></td>
                                        </tr>
                                    </tfoot>


                                </table>
                        
                </div>
             </div>
             
           

        

</div>
</main>
</body>


<style>

    .content {
        display: flex;
        flex-wrap: wrap;
        justify-content: space-between;
        padding: 20px 0;
    }


    .inputbox {
        display: flex;
        width: calc(100% / 3 - 15px);
        flex-direction: column;
        margin: 2px 0;
    }

        .inputbox:nth-child(2n) {
            justify-content: space-between;
        }

    .select-box:nth-child(4n) {
        justify-content: space-between;
    }

    .inputbox label {
        width: 95%;
        color: #dc3545;
        font-weight: bold;
        margin: 5px 0;
        text-align: left;
    }



    .inputbox input {
        height: 40px;
        width: 95%;
        padding: 0 10px;
        border-radius: 5px;
        border: 2px solid #dc3545;
        outline: none;
        display: flex;
        font-weight: 600;
        font-size: 18px;
        color: #dc3545;
        background: transparent;
    }

        .inputbox input:is(:focus, :valid) {
            box-shadow: 0 3px 6px rgba(0,0,0,0.2);
        }

    .selectbox {
        display: flex;
        flex-wrap: wrap;
        width: 50%;
        padding-bottom: 15px;
    }

        .selectbox select {
            height: 40px;
            width: 95%;
            padding: 0 10px;
            border-radius: 5px;
            border: 2px solid #dc3545;
            outline: none;
            background: transparent;
            color: #dc3545;
            font-weight: bolder;
        }

            .selectbox select:is(:focus, :valid) {
                box-shadow: 0 3px 6px rgba(0,0,0,0.2);
            }

        .selectbox label {
            width: 95%;
            color: #dc3545;
            font-weight: bold;
            margin: 5px 3px;
            text-align: left;
        }


    .btns {
        width: 40%;
        padding: 7px;
        font-weight: bolder;
        font-size: 20px;
        color: #fff;
        border: .2rem solid #dc3545;
        border-radius: 5px;
        background: #dc3545;
        ;
    }

        .btns:hover {
            background: transparent;
            color: #dc3545;
        }

</style>