bbms/Pages/users/changepass.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Data.SqlClient;

namespace bbms.Pages.users
{
    public class changepassModel : PageModel
    {
        string connectionString = "Data Source=DESKTOP-9DNNVCS\\SQLEXPRESS;Initial Catalog=blooddb;Integrated Security=True";
        public string errormsg = "";
        public string successmsg = "";
        public void OnGet()
        {
        }
      
        public void OnPost()
        {
            string name = Request.Form["username"];
            string old_pass = Request.Form["old"];
            string newpass = Request.Form["new"];
            SqlConnection con = new SqlConnection(connectionString);
            con.Open();
            string sql = "SELECT * FROM users where UserName = '" + name + "' and Password = '" + old_pass + "' ";
            SqlCommand cmd = new SqlCommand(sql, con);
            SqlDataReader reader = cmd.ExecuteReader();

            if (reader.Read())
            {
                try
                {
                    //update password
                    SqlConnection conn = new SqlConnection(connectionString);
                    conn.Open();
                    string qry = "UPDATE users SET Password = '" + newpass + "' WHERE UserName = '" + name + "'";
                    SqlCommand sqlCommand = new SqlCommand(qry, conn);
                    sqlCommand.ExecuteNonQuery();
                    Response.Redirect("/Index");
                }
                catch(Exception ex)
                {
                    errormsg = ex.Message;
                    return;
                }
            }

            else
            {
                errormsg = "Old Password Incorrect";
                return;
            }
        }
    }
}

bbms/Pages/users/view_users.cshtml.cs
using bbms.Pages.patients;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Data.SqlClient;

namespace bbms.Pages.users
{
    public class view_usersModel : PageModel
    {
        string connectionString = "Data Source=DESKTOP-9DNNVCS\\SQLEXPRESS;Initial Catalog=blooddb;Integrated Security=True";
        public string errormsg = "";
        public string successmsg = "";
        public string updatemsg = "";
        public List<userinfo> userlist = new List<userinfo>();
        public userinfo userinfo = new userinfo();
        public void OnGet()
        {
            try
            {
                SqlConnection con = new SqlConnection(connectionString);
                con.Open();
                string sql = "select * from users";
                SqlCommand cmd = new SqlCommand(sql, con);
                SqlDataReader reader = cmd.ExecuteReader();
                while (reader.Read())
                {
                    userinfo info = new userinfo();
                    info.id = reader.GetInt32(0);
                    info.name = reader.GetString(1);
                    info.full = reader.GetString(2);
                    info.password = reader.GetString(3);
                    info.role = reader.GetString(4);
                    userlist.Add(info);
                }
            }
            catch (Exception ex)
            {
                errormsg = ex.Message;
                return;
            }

            try
            {

                string id = Request.Query["id"];

                SqlConnection sqlConnection = new SqlConnection(connectionString);
                sqlConnection.Open();
                string sql = "SELECT * FROM users where UserID = '" + id + "'";
                SqlCommand cmd = new SqlCommand(sql, sqlConnection);
                SqlDataReader reader = cmd.ExecuteReader();
                while (reader.Read())
                {

                    userinfo.id = reader.GetInt32(0);
                    userinfo.name = reader.GetString(1);
                    userinfo.full = reader.GetString(2);
                    userinfo.password = reader.GetString(3);
                    userinfo.role = reader.GetString(4);
                }

            }
            catch (Exception ex)
            {
                errormsg = ex.Message;
            }

        }

        public void OnPostUpdate()
        {
            string id = Request.Form["id"];
            string name = Request.Form["name"];
            string full = Request.Form["full"];
            string password = Request.Form["password"];
            string role = Request.Form["role"];
            try
            {
                //update
                SqlConnection sqlConnection = new SqlConnection(connectionString);
                sqlConnection.Open();
                string sql = "Update users set UserName = '" + name + "',FullName = '" + full + "',Password = '" + password + "',Role ='" + role + "' where UserID = '" + id + "'";
                SqlCommand sqlCommand = new SqlCommand(sql, sqlConnection);
                sqlCommand.ExecuteNonQuery();
                sqlConnection.Close();
                
                // end update
            }

            catch (Exception ex)
            {
                errormsg = ex.Message;
                return;

            }
            Response.Redirect("/users/view_users");
        }

        public void OnPost()
        {
            string name = Request.Form["name"];
            string full = Request.Form["full"];
            string password = Request.Form["password"];
            string role = Request.Form["role"];
            try
            {
                //sava
                SqlConnection sqlConnection = new SqlConnection(connectionString);
                sqlConnection.Open();
                string sql = "INSERT INTO users (UserName,FullName,Password,Role) VALUES('" + name + "', '" + full + "', '" + password + "', '" + role + "')";
                SqlCommand sqlCommand = new SqlCommand(sql, sqlConnection);
                sqlCommand.ExecuteNonQuery();
                
                // end save
            }

            catch (Exception ex)
            {
                errormsg = ex.Message;

            }
            Response.Redirect("/users/view_users");



        }
    }

    public class userinfo
    {
        public int id;
        public string name;
        public string full;
        public string password;
        public string role;
    }
}

bbms/Pages/users/changepass.cshtml
@page
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@using Microsoft.AspNetCore.Http;
@inject IHttpContextAccessor HttpContextAccessor;

@model bbms.Pages.users.changepassModel
@{
}

@if (@HttpContextAccessor.HttpContext.Session.GetString("user") == null)
{
    Response.Redirect("/Index");
}

@if (Model.errormsg.Length > 0)
{
    <div class="alert alert-danger text-dark alert-dismissible fade show" role="alert">
        @Model.errormsg
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">x</button>
    </div>
}

<div class="container">
    <center>
        <h1 style=" font-family : Tahoma; font-weight : bolder; color :var(--sidebar-color);"> Blood Bank System</h1>
        <h2 style=" font-family : Tahoma; font-weight : bolder; color :var(--sidebar-color);">Change Password</h2>
        <i class="fas fa-droplet" style="color :var(--sidebar-color);"></i>
    </center>
    <div class="dcontainer">
        <div class="form-container forget">
            <form method="POST" onsubmit="return validate()">

                <h1>Change Password</h1>
                <input type="hidden" name="username" value="@HttpContextAccessor.HttpContext.Session.GetString("user")" />
                <input type="password" name="old" placeholder="Old Password" autocomplete="off" required>
                <input type="password" name="new" id="new_password" placeholder="New password" autocomplete="off" required>
                <input type="password" name="confirm" id="confirm_password" placeholder="Confirm" autocomplete="off" required>
                <button type="submit" name="signup">Change</button>
            </form>
        </div>
        <div class="toggle-container">
            <div class="toggle">
                <div class="toggle-panel bx-toggle-right">
                    <img src="~/images/ch.png"/>
                </div>
            </div>
        </div>
    </div>
</div>
<br>
<br>




<style>
    * {
        font-family: Tahoma;
    }

    .dcontainer {
        background-color: #fff;
        border-radius: 30px;
        box-shadow: 0 0 25px #dc3545;
        position: relative;
        overflow: hidden;
        width:90%;
        height: 480px;
        margin-left: 10%;
        border: 3px solid #dc3545;
        margin-top: 8%;
    }

        .dcontainer button {
            background: #dc3545;
            color: #fff;
            font-size: 18px;
            padding: 10px 45px;
            border: 1px solid transparent;
            border-radius: 8px;
            font-weight: 900;
            letter-spacing: 0.5px;
            text-transform: uppercase;
            margin-top: 10px;
            cursor: pointer;
        }

        .dcontainer form {
            background: #fff;
            display: flex;
            align-items: center;
            justify-content: center;
            flex-direction: column;
            padding: 0 40px;
            height: 100%;
        }

        .dcontainer input {
            background: #eee;
            border: none;
            margin: 10px 0;
            padding: 10px 15px;
            font-size: 18px;
            border-radius: 8px;
            width: 80%;
            outline: none;
        }

    .form-container {
        position: absolute;
        top: 0;
        height: 100%;
        transition: all 0.6s ease-in-out;
    }

    .forget {
        right: 0;
        width: 50%;
    }


    .toggle-container {
        position: absolute;
        top: 0;
        right: 30%;
        width: 72%;
        height: 100%;
        overflow: hidden;
        transition: all 0.6s ease-in-out;
        border-radius: 150px 0 0 100px;
        z-index: 1000;
    }


    h1 {
        color: #000;
        font-size:24px;
        color: #dc3545;
        font-weight:bolder;
    }

</style>

<script>
    function validate(){
        var new_password = document.getElementById("new_password").value;
        var confirm_password = document.getElementById("confirm_password").value;
        if (new_password != confirm_password) {
            alert("Password didn't match!!.");
            return false;
        }
        else {
            return true;
        }
    }
</script>

bbms/Pages/users/logout.cshtml
@page
@{
    HttpContext.Session.Clear();
    Response.Redirect("/Index");
}

bbms/Pages/users/user_delete.cshtml
@page

@using System.Data.SqlClient;

@{
    string errormsg = "";
    string connectionString = "Data Source=DESKTOP-9DNNVCS\\SQLEXPRESS;Initial Catalog=blooddb;Integrated Security=True";
    string id = Request.Query["delete"];


    try
    {
        SqlConnection con = new SqlConnection(connectionString);
        con.Open();
        string sql = "Delete from users where UserID = '" + id + "'";
        SqlCommand cmd = new SqlCommand(sql, con);
        cmd.ExecuteNonQuery();
        con.Close();
        errormsg = "Data Deleted Successfully";
        Response.Redirect("/users/view_users");
        return;

    }

    catch (Exception ex)
    {
        return;
    }

  
   
}

bbms/Pages/users/view_users.cshtml
@page
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@using Microsoft.AspNetCore.Http;
@inject IHttpContextAccessor HttpContextAccessor;


@model bbms.Pages.users.view_usersModel
@{
}

@if (@HttpContextAccessor.HttpContext.Session.GetString("user") == null)
{
    Response.Redirect("/Index");
}

@if (@HttpContextAccessor.HttpContext.Session.GetString("role") == "User")
{
    Response.Redirect("/dashboard/dashboard");
}


@if (Model.errormsg.Length > 0)
{
    <div class="alert alert-danger text-dark alert-dismissible fade show" role="alert">
        @Model.errormsg
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">x</button>
    </div>
}

@if (Model.successmsg.Length > 0)
{
    <div class="alert alert-info text-dark alert-dismissible fade show" role="alert">
        @Model.successmsg
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">x</button>
    </div>
}


<body class="bg-content">

    <main class="dashboard">
        <div class="container">

            <br />
            <center>
                <h1 style=" font-family : Tahoma; font-weight : bolder; color :var(--sidebar-color);"> Blood Bank System</h1>
                <h2 style=" font-family : Tahoma; font-weight : bolder; color :var(--sidebar-color);">Users</h2>
                <i class="fas fa-droplet" style="color :var(--sidebar-color);"></i>
            </center>
                    <form method="POST">

                        <div class="content">
                            <div class="inputbox">
                                <label>UserName</label>
                                <input type="text" name="name" required value="@Model.userinfo.name" autocomplete="off" />
                                <input type="hidden" name="id" readonly value="@Model.userinfo.id" />
                            </div>

                            <div class="inputbox">
                                <label>FullName</label>
                                <input type="text" name="full" required value="@Model.userinfo.full" autocomplete="off" />
                            </div>
                            <div class="inputbox">
                                <label>Password</label>
                                <input type="password" name="password" value="@Model.userinfo.password" required autocomplete="off" />
                            </div>
                            <div class="selectbox">
                                <label>Role</label>
                                <select name="role" required>
                                    <option value="@Model.userinfo.role">@Model.userinfo.role</option>
                                    <option value="Admin">Admin</option>
                                    <option value="User">User</option>
                                </select>
                            </div>
                        </div>
                        <center>
                            <a href="" data-bs-toggle="modal" data-bs-target="#add" class="btn btns"><i class="fas fa-add"></i> Add</a>
                            <button name="update" id="btnUpdate" asp-page-handler="Update" type="submit" class="btns"><i class="fas fa-edit"></i> Update</button>
                        </center>
                    </form>
            <br /><br /><br /><br />

            <table class="table table-bordered table-stripped" id="mytable" style="width: 115%;">
                <thead class="bg-danger text-white" style="font-family:Tahoma; text-align:center; font-size:16px; font-weight:700;">
                <tr>
                <th>UID</th>
                <th>UName</th>
                <th>Full</th>
                <th>Password</th>
                <th>Role</th>
                <th>Action</th>
                </tr>
                </thead>
                <tbody>
                    @foreach (var row in Model.userlist)
                    {
                        <tr style="color: red; font-family:Tahoma; text-align:center; font-size:16px; font-weight:700;">
                            <td class="patient_id">@row.id</td>
                            <td>@row.name</td>
                            <td>@row.full</td>
                            <td>@row.password</td>
                            <td>@row.role</td>
                            <td>
                                <a href="/users/view_users?id=@row.id" class="btn btn-success btn-sm text-light"><i class="fas fa-pen"></i></a>
                                <a href="/users/user_delete?delete=@row.id" class="btn btn-danger btn-sm" onclick="return confirm('Are you sure you want to delete this data?')"><i class="fas fa-trash"></i></a>
                            </td>

                        </tr>
                    }
                </tbody>
                <tfoot>
                    <tr class="" style="background:red">
                        <td colspan="6" style="height: 10px"></td>
                    </tr>
                </tfoot>


            </table>
        </div>
    </main>
</body>

<style>

  
    .content {
        display: flex;
        flex-wrap: wrap;
        justify-content: space-between;
        padding: 20px 0;
    }


    form :where( .content .inputbox, .selectbox){
        display: flex;
        width: calc(100% / 4 - 5px);
        flex-direction: column;
        margin: 5px 0;
    }


    .inputbox label {
        width: 95%;
        color: #dc3545;
        font-weight: bold;
        margin: 5px 0;
        text-align: left;
    }



    .inputbox input {
        height: 40px;
        width: 95%;
        padding: 0 10px;
        border-radius: 5px;
        border: 2px solid #dc3545;
        outline: none;
        display: flex;
        font-weight: 600;
        font-size: 18px;
        color: #dc3545;
        background: transparent;
    }

        .inputbox input:is(:focus, :valid) {
            box-shadow: 0 3px 6px rgba(0,0,0,0.2);
        }

        .selectbox select {
            height: 40px;
            padding: 0 10px;
            border-radius: 5px;
            border: 2px solid #dc3545;
            outline: none;
            background: transparent;
            color: #dc3545;
            font-weight: bolder;
        }

            .selectbox select:is(:focus, :valid) {
                box-shadow: 0 3px 6px rgba(0,0,0,0.2);
            }

        .selectbox label {
            width: 95%;
            color: #dc3545;
            font-weight: bold;
            margin: 5px 3px;
            text-align: left;
        }


    .btns {
        width: 20%;
        padding: 7px;
        font-weight: bolder;
        font-size: 20px;
        color: #fff;
        border: .2rem solid #dc3545;
        border-radius: 5px;
        background: #dc3545;
        ;
    }

        .btns:hover {
            background: transparent;
            color: #dc3545;
        }

</style>

<!--model-->
<div class="modal fade" id="add" tabindex="-1" aria - labelledby="updateuserLabel" ariahidden="true">
    <div class="modal-dialog">
        <div class="modal-content" style="width:140%;">
            <div class="modal-header">
                <h1 class="modal-title fs-5" id="updateuserLabel" style=" font-family : Tahoma; font-weight : bolder; color :var(--sidebar-color);">New User</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>

            <div class="modal-body">
                <form method="Post">
                    <div class="content">
                        <div class="input_box">
                            <label>UserName</label>
                            <input type="text" name="name" required autocomplete="off" />
                        </div>

                        <div class="input_box">
                            <label>FullName</label>
                            <input type="text" name="full" required autocomplete="off" />
                        </div>
                        <div class="select_box">
                            <label>Role</label>
                            <select name="role" required>
                                <option value="">Select</option>
                                <option value="Admin">Admin</option>
                                <option value="User">User</option>
                            </select>
                        </div>
                        <div class="input_box">
                            <label>Password</label>
                            <input type="password" name="password" required autocomplete="off" />
                        </div>
                    </div>



                    <div class="modal-footer">

                        <button type="button" class="buttns" data-bs-dismiss="modal">Close</button>
                        <input name="save" type="submit" class="buttns" value="Save" />

                    </div>
                </form>
            </div>

        </div>

    </div>
</div>

<script type="text/javascript">
    $(document).ready(function () {
        $('#mytable').DataTable();
    });
    </Script>

<style>

    .content {
        display: flex;
        flex-wrap: wrap;
        justify-content: space-between;
        padding: 20px 0;
    }


    .input_box {
        display: flex;
        flex-wrap: wrap;
        width: 50%;
        padding-bottom: 15px;
    }

        .input_box:nth-child(2n) {
            justify-content: space-between;
        }

    .select_box:nth-child(4n) {
        justify-content: space-between;
    }

    .input_box label {
        width: 95%;
        color: #dc3545;
        font-weight: bold;
        margin: 5px 0;
        text-align: left;
    }



    .input_box input{
        height: 40px;
        width: 95%;
        padding: 0 10px;
        border-radius: 5px;
        border: 2px solid #dc3545;
        outline: none;
        display: flex;
        font-weight: 600;
        font-size: 18px;
        color: #dc3545;
        background : transparent;
    }

        .input_box input:is(:focus, :valid) {
            box-shadow: 0 3px 6px rgba(0,0,0,0.2);
        }

    .select_box {
        display: flex;
        flex-wrap: wrap;
        width: 50%;
        padding-bottom: 15px;
    }

        .select_box select {
            height: 40px;
            width: 95%;
            padding: 0 10px;
            border-radius: 5px;
            border: 2px solid #dc3545;
            outline: none;
            background: transparent;
            color: #dc3545;
            font-weight: bolder;
        }

            .select_box select:is(:focus, :valid) {
                box-shadow: 0 3px 6px rgba(0,0,0,0.2);
            }

        .select_box label {
            width: 95%;
            color: #dc3545;
            font-weight: bold;
            margin: 5px 3px;
            text-align: left;
        }


    .buttns{
        width: 40%;
        padding: 7px;
        font-weight: bolder;
        font-size: 20px;
        color: #fff;
        border: .2rem solid #dc3545;
        border-radius: 5px;
        background: #dc3545;
    }

        .buttns:hover {
            background: transparent;
            color: #dc3545;
        }
       .dataTables_length label{
            color: #dc3545;
            font-size: 20px;
            font-weight : bold;
            font-family: Tahoma;
        }
        .dataTables_length select{
            height: 40px;
            width: 35%;
            padding: 0 10px;
            border-radius: 5px;
            border: 2px solid #dc3545;
            outline: none;
            background: transparent;
            color: #dc3545;
            font-weight: bolder;
            margin-bottom: 1rem;
        }
        .dataTables_filter input{
         height: 40px;
         width: 80%;
        padding: 0 10px;
        border-radius: 5px;
        border: 2px solid #dc3545;
        outline: none;
        font-weight: 600;
        font-size: 18px;
        color: #dc3545;
        background : transparent;
        }

        .dataTables_filter label{
        color: #dc3545;
        font-weight: bold;
        margin: 5px 0;
        }

        #mytable_info{
            color: #dc3545;
            font-size: 20px;
            font-weight : bold;
            font-family: Tahoma;
        }
        .paginate_button.previous ,
        .paginate_button.next{
            color: #dc3545;
            font-size: 20px;
            font-weight : bold;
            font-family: Tahoma;
        }
        a.paginate_button.current{
        padding: 7px;
        font-weight: bolder;
        font-size: 20px;
        color: #fff;
        border: .2rem solid #dc3545;
        border-radius: 5px;
        background: #dc3545;
        }
     
</style>